package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Atividade generated by hbm2java
 */
public class Atividade implements java.io.Serializable {

	private int idAtividade;
	private String nome;
	private Set pacientes = new HashSet(0);

	public Atividade() {
	}

	public Atividade(int idAtividade) {
		this.idAtividade = idAtividade;
	}

	public Atividade(int idAtividade, String nome, Set pacientes) {
		this.idAtividade = idAtividade;
		this.nome = nome;
		this.pacientes = pacientes;
	}

	public int getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(int idAtividade) {
		this.idAtividade = idAtividade;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Set pacientes) {
		this.pacientes = pacientes;
	}

}
