package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private int idCategoria;
	private String nome;
	private Set jogos = new HashSet(0);
	private Set questionarios = new HashSet(0);

	public Categoria() {
	}

	public Categoria(int idCategoria, String nome) {
		this.idCategoria = idCategoria;
		this.nome = nome;
	}

	public Categoria(int idCategoria, String nome, Set jogos, Set questionarios) {
		this.idCategoria = idCategoria;
		this.nome = nome;
		this.jogos = jogos;
		this.questionarios = questionarios;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getJogos() {
		return this.jogos;
	}

	public void setJogos(Set jogos) {
		this.jogos = jogos;
	}

	public Set getQuestionarios() {
		return this.questionarios;
	}

	public void setQuestionarios(Set questionarios) {
		this.questionarios = questionarios;
	}

}
