package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Familiar generated by hbm2java
 */
public class Familiar implements java.io.Serializable {

	private int idFamiliar;
	private Morada moradaByMoradaIdMorada;
	private Morada moradaByLocalNascimentoIdMorada;
	private String nomeCompleto;
	private String nomeProprio;
	private String apelido;
	private Date dataDeNascimento;
	private String genero;
	private String estadoCivil;
	private String profissao;
	private Integer telefone;
	private Boolean ECuidador;
	private String nomeUtilizador;
	private String password;
	private Date dataDeObito;
	private Set relacaoFamiliarFamiliarsForFamiliarIdFamiliar = new HashSet(0);
	private Set eventos = new HashSet(0);
	private Set relacaoPacienteFamiliars = new HashSet(0);
	private Set relacaoFamiliarFamiliarsForFamiliarIdFamiliar1 = new HashSet(0);

	public Familiar() {
	}

	public Familiar(int idFamiliar, Morada moradaByMoradaIdMorada,
			Morada moradaByLocalNascimentoIdMorada) {
		this.idFamiliar = idFamiliar;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
	}

	public Familiar(int idFamiliar, Morada moradaByMoradaIdMorada,
			Morada moradaByLocalNascimentoIdMorada, String nomeCompleto,
			String nomeProprio, String apelido, Date dataDeNascimento,
			String genero, String estadoCivil, String profissao,
			Integer telefone, Boolean ECuidador, String nomeUtilizador,
			String password, Date dataDeObito,
			Set relacaoFamiliarFamiliarsForFamiliarIdFamiliar, Set eventos,
			Set relacaoPacienteFamiliars,
			Set relacaoFamiliarFamiliarsForFamiliarIdFamiliar1) {
		this.idFamiliar = idFamiliar;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.nomeCompleto = nomeCompleto;
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.dataDeNascimento = dataDeNascimento;
		this.genero = genero;
		this.estadoCivil = estadoCivil;
		this.profissao = profissao;
		this.telefone = telefone;
		this.ECuidador = ECuidador;
		this.nomeUtilizador = nomeUtilizador;
		this.password = password;
		this.dataDeObito = dataDeObito;
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar = relacaoFamiliarFamiliarsForFamiliarIdFamiliar;
		this.eventos = eventos;
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar1 = relacaoFamiliarFamiliarsForFamiliarIdFamiliar1;
	}

	public int getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(int idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	public Morada getMoradaByMoradaIdMorada() {
		return this.moradaByMoradaIdMorada;
	}

	public void setMoradaByMoradaIdMorada(Morada moradaByMoradaIdMorada) {
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
	}

	public Morada getMoradaByLocalNascimentoIdMorada() {
		return this.moradaByLocalNascimentoIdMorada;
	}

	public void setMoradaByLocalNascimentoIdMorada(
			Morada moradaByLocalNascimentoIdMorada) {
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
	}

	public String getNomeCompleto() {
		return this.nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	public String getNomeProprio() {
		return this.nomeProprio;
	}

	public void setNomeProprio(String nomeProprio) {
		this.nomeProprio = nomeProprio;
	}

	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public Date getDataDeNascimento() {
		return this.dataDeNascimento;
	}

	public void setDataDeNascimento(Date dataDeNascimento) {
		this.dataDeNascimento = dataDeNascimento;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public String getProfissao() {
		return this.profissao;
	}

	public void setProfissao(String profissao) {
		this.profissao = profissao;
	}

	public Integer getTelefone() {
		return this.telefone;
	}

	public void setTelefone(Integer telefone) {
		this.telefone = telefone;
	}

	public Boolean getECuidador() {
		return this.ECuidador;
	}

	public void setECuidador(Boolean ECuidador) {
		this.ECuidador = ECuidador;
	}

	public String getNomeUtilizador() {
		return this.nomeUtilizador;
	}

	public void setNomeUtilizador(String nomeUtilizador) {
		this.nomeUtilizador = nomeUtilizador;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getDataDeObito() {
		return this.dataDeObito;
	}

	public void setDataDeObito(Date dataDeObito) {
		this.dataDeObito = dataDeObito;
	}

	public Set getRelacaoFamiliarFamiliarsForFamiliarIdFamiliar() {
		return this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar;
	}

	public void setRelacaoFamiliarFamiliarsForFamiliarIdFamiliar(
			Set relacaoFamiliarFamiliarsForFamiliarIdFamiliar) {
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar = relacaoFamiliarFamiliarsForFamiliarIdFamiliar;
	}

	public Set getEventos() {
		return this.eventos;
	}

	public void setEventos(Set eventos) {
		this.eventos = eventos;
	}

	public Set getRelacaoPacienteFamiliars() {
		return this.relacaoPacienteFamiliars;
	}

	public void setRelacaoPacienteFamiliars(Set relacaoPacienteFamiliars) {
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
	}

	public Set getRelacaoFamiliarFamiliarsForFamiliarIdFamiliar1() {
		return this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar1;
	}

	public void setRelacaoFamiliarFamiliarsForFamiliarIdFamiliar1(
			Set relacaoFamiliarFamiliarsForFamiliarIdFamiliar1) {
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar1 = relacaoFamiliarFamiliarsForFamiliarIdFamiliar1;
	}

}
