package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Interesse generated by hbm2java
 */
public class Interesse implements java.io.Serializable {

	private int idInteresse;
	private String nome;
	private Set pacientes = new HashSet(0);

	public Interesse() {
	}

	public Interesse(int idInteresse, String nome) {
		this.idInteresse = idInteresse;
		this.nome = nome;
	}

	public Interesse(int idInteresse, String nome, Set pacientes) {
		this.idInteresse = idInteresse;
		this.nome = nome;
		this.pacientes = pacientes;
	}

	public int getIdInteresse() {
		return this.idInteresse;
	}

	public void setIdInteresse(int idInteresse) {
		this.idInteresse = idInteresse;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Set pacientes) {
		this.pacientes = pacientes;
	}

}
