package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Interacao generated by hbm2java
 */
public class Interacao implements java.io.Serializable {

	private int idInteracao;
	private Paciente paciente;
	private Date data;
	private Set jogos = new HashSet(0);
	private Set questionarios = new HashSet(0);

	public Interacao() {
	}

	public Interacao(int idInteracao, Paciente paciente, Date data) {
		this.idInteracao = idInteracao;
		this.paciente = paciente;
		this.data = data;
	}

	public Interacao(int idInteracao, Paciente paciente, Date data, Set jogos,
			Set questionarios) {
		this.idInteracao = idInteracao;
		this.paciente = paciente;
		this.data = data;
		this.jogos = jogos;
		this.questionarios = questionarios;
	}

	public int getIdInteracao() {
		return this.idInteracao;
	}

	public void setIdInteracao(int idInteracao) {
		this.idInteracao = idInteracao;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Set getJogos() {
		return this.jogos;
	}

	public void setJogos(Set jogos) {
		this.jogos = jogos;
	}

	public Set getQuestionarios() {
		return this.questionarios;
	}

	public void setQuestionarios(Set questionarios) {
		this.questionarios = questionarios;
	}

}
