package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Morada generated by hbm2java
 */
public class Morada implements java.io.Serializable {

	private int idMorada;
	private String pais;
	private String regiao;
	private String cidade;
	private Set pacientesForLocalNascimentoIdMorada = new HashSet(0);
	private Set familiarsForMoradaIdMorada = new HashSet(0);
	private Set familiarsForLocalNascimentoIdMorada = new HashSet(0);
	private Set eventos = new HashSet(0);
	private Set pacientesForMoradaIdMorada = new HashSet(0);

	public Morada() {
	}

	public Morada(int idMorada) {
		this.idMorada = idMorada;
	}

	public Morada(int idMorada, String pais, String regiao, String cidade,
			Set pacientesForLocalNascimentoIdMorada,
			Set familiarsForMoradaIdMorada,
			Set familiarsForLocalNascimentoIdMorada, Set eventos,
			Set pacientesForMoradaIdMorada) {
		this.idMorada = idMorada;
		this.pais = pais;
		this.regiao = regiao;
		this.cidade = cidade;
		this.pacientesForLocalNascimentoIdMorada = pacientesForLocalNascimentoIdMorada;
		this.familiarsForMoradaIdMorada = familiarsForMoradaIdMorada;
		this.familiarsForLocalNascimentoIdMorada = familiarsForLocalNascimentoIdMorada;
		this.eventos = eventos;
		this.pacientesForMoradaIdMorada = pacientesForMoradaIdMorada;
	}

	public int getIdMorada() {
		return this.idMorada;
	}

	public void setIdMorada(int idMorada) {
		this.idMorada = idMorada;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getRegiao() {
		return this.regiao;
	}

	public void setRegiao(String regiao) {
		this.regiao = regiao;
	}

	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public Set getPacientesForLocalNascimentoIdMorada() {
		return this.pacientesForLocalNascimentoIdMorada;
	}

	public void setPacientesForLocalNascimentoIdMorada(
			Set pacientesForLocalNascimentoIdMorada) {
		this.pacientesForLocalNascimentoIdMorada = pacientesForLocalNascimentoIdMorada;
	}

	public Set getFamiliarsForMoradaIdMorada() {
		return this.familiarsForMoradaIdMorada;
	}

	public void setFamiliarsForMoradaIdMorada(Set familiarsForMoradaIdMorada) {
		this.familiarsForMoradaIdMorada = familiarsForMoradaIdMorada;
	}

	public Set getFamiliarsForLocalNascimentoIdMorada() {
		return this.familiarsForLocalNascimentoIdMorada;
	}

	public void setFamiliarsForLocalNascimentoIdMorada(
			Set familiarsForLocalNascimentoIdMorada) {
		this.familiarsForLocalNascimentoIdMorada = familiarsForLocalNascimentoIdMorada;
	}

	public Set getEventos() {
		return this.eventos;
	}

	public void setEventos(Set eventos) {
		this.eventos = eventos;
	}

	public Set getPacientesForMoradaIdMorada() {
		return this.pacientesForMoradaIdMorada;
	}

	public void setPacientesForMoradaIdMorada(Set pacientesForMoradaIdMorada) {
		this.pacientesForMoradaIdMorada = pacientesForMoradaIdMorada;
	}

}
