package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

	private int idPaciente;
	private Morada moradaByLocalNascimentoIdMorada;
	private Morada moradaByMoradaIdMorada;
	private Tecnico tecnico;
	private String nomeCompleto;
	private String nomeProprio;
	private String apelido;
	private Date dataDeNascimento;
	private String genero;
	private String profissao;
	private String escolaridade;
	private String estadoCivil;
	private Integer nivelDeDoenca;
	private String nomeMedico;
	private String especialidadeMedico;
	private Integer nivelSessao;
	private Set atividades = new HashSet(0);
	private Set interacaos = new HashSet(0);
	private Set interesses = new HashSet(0);
	private Set relacaoPacienteFamiliars = new HashSet(0);
	private Set eventos = new HashSet(0);
	private Set relacaoFamiliarFamiliars = new HashSet(0);

	public Paciente() {
	}

	public Paciente(int idPaciente, Morada moradaByLocalNascimentoIdMorada,
			Morada moradaByMoradaIdMorada, Tecnico tecnico) {
		this.idPaciente = idPaciente;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.tecnico = tecnico;
	}

	public Paciente(int idPaciente, Morada moradaByLocalNascimentoIdMorada,
			Morada moradaByMoradaIdMorada, Tecnico tecnico,
			String nomeCompleto, String nomeProprio, String apelido,
			Date dataDeNascimento, String genero, String profissao,
			String escolaridade, String estadoCivil, Integer nivelDeDoenca,
			String nomeMedico, String especialidadeMedico, Integer nivelSessao,
			Set atividades, Set interacaos, Set interesses,
			Set relacaoPacienteFamiliars, Set eventos,
			Set relacaoFamiliarFamiliars) {
		this.idPaciente = idPaciente;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.tecnico = tecnico;
		this.nomeCompleto = nomeCompleto;
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.dataDeNascimento = dataDeNascimento;
		this.genero = genero;
		this.profissao = profissao;
		this.escolaridade = escolaridade;
		this.estadoCivil = estadoCivil;
		this.nivelDeDoenca = nivelDeDoenca;
		this.nomeMedico = nomeMedico;
		this.especialidadeMedico = especialidadeMedico;
		this.nivelSessao = nivelSessao;
		this.atividades = atividades;
		this.interacaos = interacaos;
		this.interesses = interesses;
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
		this.eventos = eventos;
		this.relacaoFamiliarFamiliars = relacaoFamiliarFamiliars;
	}

	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	public Morada getMoradaByLocalNascimentoIdMorada() {
		return this.moradaByLocalNascimentoIdMorada;
	}

	public void setMoradaByLocalNascimentoIdMorada(
			Morada moradaByLocalNascimentoIdMorada) {
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
	}

	public Morada getMoradaByMoradaIdMorada() {
		return this.moradaByMoradaIdMorada;
	}

	public void setMoradaByMoradaIdMorada(Morada moradaByMoradaIdMorada) {
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
	}

	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	public String getNomeCompleto() {
		return this.nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	public String getNomeProprio() {
		return this.nomeProprio;
	}

	public void setNomeProprio(String nomeProprio) {
		this.nomeProprio = nomeProprio;
	}

	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public Date getDataDeNascimento() {
		return this.dataDeNascimento;
	}

	public void setDataDeNascimento(Date dataDeNascimento) {
		this.dataDeNascimento = dataDeNascimento;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getProfissao() {
		return this.profissao;
	}

	public void setProfissao(String profissao) {
		this.profissao = profissao;
	}

	public String getEscolaridade() {
		return this.escolaridade;
	}

	public void setEscolaridade(String escolaridade) {
		this.escolaridade = escolaridade;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public Integer getNivelDeDoenca() {
		return this.nivelDeDoenca;
	}

	public void setNivelDeDoenca(Integer nivelDeDoenca) {
		this.nivelDeDoenca = nivelDeDoenca;
	}

	public String getNomeMedico() {
		return this.nomeMedico;
	}

	public void setNomeMedico(String nomeMedico) {
		this.nomeMedico = nomeMedico;
	}

	public String getEspecialidadeMedico() {
		return this.especialidadeMedico;
	}

	public void setEspecialidadeMedico(String especialidadeMedico) {
		this.especialidadeMedico = especialidadeMedico;
	}

	public Integer getNivelSessao() {
		return this.nivelSessao;
	}

	public void setNivelSessao(Integer nivelSessao) {
		this.nivelSessao = nivelSessao;
	}

	public Set getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Set atividades) {
		this.atividades = atividades;
	}

	public Set getInteracaos() {
		return this.interacaos;
	}

	public void setInteracaos(Set interacaos) {
		this.interacaos = interacaos;
	}

	public Set getInteresses() {
		return this.interesses;
	}

	public void setInteresses(Set interesses) {
		this.interesses = interesses;
	}

	public Set getRelacaoPacienteFamiliars() {
		return this.relacaoPacienteFamiliars;
	}

	public void setRelacaoPacienteFamiliars(Set relacaoPacienteFamiliars) {
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
	}

	public Set getEventos() {
		return this.eventos;
	}

	public void setEventos(Set eventos) {
		this.eventos = eventos;
	}

	public Set getRelacaoFamiliarFamiliars() {
		return this.relacaoFamiliarFamiliars;
	}

	public void setRelacaoFamiliarFamiliars(Set relacaoFamiliarFamiliars) {
		this.relacaoFamiliarFamiliars = relacaoFamiliarFamiliars;
	}

}
