package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

/**
 * RelacaoFamiliarFamiliarId generated by hbm2java
 */
public class RelacaoFamiliarFamiliarId implements java.io.Serializable {

	private int idRelacaoFamiliarFamiliar;
	private int familiarIdFamiliar1;
	private int familiarIdFamiliar;

	public RelacaoFamiliarFamiliarId() {
	}

	public RelacaoFamiliarFamiliarId(int idRelacaoFamiliarFamiliar,
			int familiarIdFamiliar1, int familiarIdFamiliar) {
		this.idRelacaoFamiliarFamiliar = idRelacaoFamiliarFamiliar;
		this.familiarIdFamiliar1 = familiarIdFamiliar1;
		this.familiarIdFamiliar = familiarIdFamiliar;
	}

	public int getIdRelacaoFamiliarFamiliar() {
		return this.idRelacaoFamiliarFamiliar;
	}

	public void setIdRelacaoFamiliarFamiliar(int idRelacaoFamiliarFamiliar) {
		this.idRelacaoFamiliarFamiliar = idRelacaoFamiliarFamiliar;
	}

	public int getFamiliarIdFamiliar1() {
		return this.familiarIdFamiliar1;
	}

	public void setFamiliarIdFamiliar1(int familiarIdFamiliar1) {
		this.familiarIdFamiliar1 = familiarIdFamiliar1;
	}

	public int getFamiliarIdFamiliar() {
		return this.familiarIdFamiliar;
	}

	public void setFamiliarIdFamiliar(int familiarIdFamiliar) {
		this.familiarIdFamiliar = familiarIdFamiliar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelacaoFamiliarFamiliarId))
			return false;
		RelacaoFamiliarFamiliarId castOther = (RelacaoFamiliarFamiliarId) other;

		return (this.getIdRelacaoFamiliarFamiliar() == castOther
				.getIdRelacaoFamiliarFamiliar())
				&& (this.getFamiliarIdFamiliar1() == castOther
						.getFamiliarIdFamiliar1())
				&& (this.getFamiliarIdFamiliar() == castOther
						.getFamiliarIdFamiliar());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRelacaoFamiliarFamiliar();
		result = 37 * result + this.getFamiliarIdFamiliar1();
		result = 37 * result + this.getFamiliarIdFamiliar();
		return result;
	}

}
