package db.models;

// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

/**
 * RelacaoFamiliarFamiliar generated by hbm2java
 */
public class RelacaoFamiliarFamiliar implements java.io.Serializable {

	private RelacaoFamiliarFamiliarId id;
	private Familiar familiarByFamiliarIdFamiliar;
	private Familiar familiarByFamiliarIdFamiliar1;
	private Paciente paciente;
	private String tipoRelacao;

	public RelacaoFamiliarFamiliar() {
	}

	public RelacaoFamiliarFamiliar(RelacaoFamiliarFamiliarId id,
			Familiar familiarByFamiliarIdFamiliar,
			Familiar familiarByFamiliarIdFamiliar1, Paciente paciente) {
		this.id = id;
		this.familiarByFamiliarIdFamiliar = familiarByFamiliarIdFamiliar;
		this.familiarByFamiliarIdFamiliar1 = familiarByFamiliarIdFamiliar1;
		this.paciente = paciente;
	}

	public RelacaoFamiliarFamiliar(RelacaoFamiliarFamiliarId id,
			Familiar familiarByFamiliarIdFamiliar,
			Familiar familiarByFamiliarIdFamiliar1, Paciente paciente,
			String tipoRelacao) {
		this.id = id;
		this.familiarByFamiliarIdFamiliar = familiarByFamiliarIdFamiliar;
		this.familiarByFamiliarIdFamiliar1 = familiarByFamiliarIdFamiliar1;
		this.paciente = paciente;
		this.tipoRelacao = tipoRelacao;
	}

	public RelacaoFamiliarFamiliarId getId() {
		return this.id;
	}

	public void setId(RelacaoFamiliarFamiliarId id) {
		this.id = id;
	}

	public Familiar getFamiliarByFamiliarIdFamiliar() {
		return this.familiarByFamiliarIdFamiliar;
	}

	public void setFamiliarByFamiliarIdFamiliar(
			Familiar familiarByFamiliarIdFamiliar) {
		this.familiarByFamiliarIdFamiliar = familiarByFamiliarIdFamiliar;
	}

	public Familiar getFamiliarByFamiliarIdFamiliar1() {
		return this.familiarByFamiliarIdFamiliar1;
	}

	public void setFamiliarByFamiliarIdFamiliar1(
			Familiar familiarByFamiliarIdFamiliar1) {
		this.familiarByFamiliarIdFamiliar1 = familiarByFamiliarIdFamiliar1;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public String getTipoRelacao() {
		return this.tipoRelacao;
	}

	public void setTipoRelacao(String tipoRelacao) {
		this.tipoRelacao = tipoRelacao;
	}

}
