package db.models;
// default package
// Generated 10/fev/2015 20:18:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Tecnico generated by hbm2java
 */
public class Tecnico implements java.io.Serializable {

	private int idTecnico;
	private String nomeCompleto;
	private String nomeProprio;
	private String apelido;
	private String nomeUtilizador;
	private String password;
	private String email;
	private Set pacientes = new HashSet(0);

	public Tecnico() {
	}

	public Tecnico(int idTecnico, String nomeUtilizador, String password) {
		this.idTecnico = idTecnico;
		this.nomeUtilizador = nomeUtilizador;
		this.password = password;
	}

	public Tecnico(int idTecnico, String nomeCompleto, String nomeProprio,
			String apelido, String nomeUtilizador, String password,
			String email, Set pacientes) {
		this.idTecnico = idTecnico;
		this.nomeCompleto = nomeCompleto;
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.nomeUtilizador = nomeUtilizador;
		this.password = password;
		this.email = email;
		this.pacientes = pacientes;
	}

	public int getIdTecnico() {
		return this.idTecnico;
	}

	public void setIdTecnico(int idTecnico) {
		this.idTecnico = idTecnico;
	}

	public String getNomeCompleto() {
		return this.nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	public String getNomeProprio() {
		return this.nomeProprio;
	}

	public void setNomeProprio(String nomeProprio) {
		this.nomeProprio = nomeProprio;
	}

	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public String getNomeUtilizador() {
		return this.nomeUtilizador;
	}

	public void setNomeUtilizador(String nomeUtilizador) {
		this.nomeUtilizador = nomeUtilizador;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Set pacientes) {
		this.pacientes = pacientes;
	}

}
