package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Atividade generated by hbm2java
 */
@Entity
public class Atividade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idAtividade;
	private String nome;
	private List<Paciente> pacientes = new ArrayList<Paciente>(0);

	public Atividade() {
	}

	public Atividade(int idAtividade) {
		this.idAtividade = idAtividade;
	}

	public Atividade(int idAtividade, String nome, List<Paciente> pacientes) {
		this.idAtividade = idAtividade;
		this.nome = nome;
		this.pacientes = pacientes;
	}

	public int getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(int idAtividade) {
		this.idAtividade = idAtividade;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
