package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Jogo generated by hbm2java
 */
@Entity
public class Jogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idJogo;
	@ManyToOne
	private Categoria categoria;
	@ManyToOne
	private Interacao interacao;
	private String nome;
	private String nivel;

	public Jogo() {
	}

	public Jogo(int idJogo, Categoria categoria, Interacao interacao, String nome, String nivel) {
		this.idJogo = idJogo;
		this.categoria = categoria;
		this.interacao = interacao;
		this.nome = nome;
		this.nivel = nivel;
	}

	public int getIdJogo() {
		return this.idJogo;
	}

	public void setIdJogo(int idJogo) {
		this.idJogo = idJogo;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Interacao getInteracao() {
		return this.interacao;
	}

	public void setInteracao(Interacao interacao) {
		this.interacao = interacao;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

}
