package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Morada generated by hbm2java
 */
@Entity
public class Morada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idMorada;
	private String pais;
	private String regiao;
	private String cidade;
	
	//TODO preencher valores de objectos
	private List<?> familiarsForMoradaIdMorada = new ArrayList<Object>(0);
	private List<?> familiarsForLocalNascimentoIdMorada = new ArrayList<Object>(0);
	private List<?> eventos = new ArrayList<Object>(0);
	private List<?> pacientesForMoradaIdMorada = new ArrayList<Object>(0);
	private List<?> pacientesForLocalNascimentoIdMorada = new ArrayList<Object>(0);

	public Morada() {
	}

	public Morada(int idMorada) {
		this.idMorada = idMorada;
	}

	public Morada(int idMorada, String pais, String regiao, String cidade, List<?> familiarsForMoradaIdMorada,
			List<?> familiarsForLocalNascimentoIdMorada, List<?> eventos, List<?> pacientesForMoradaIdMorada,
			List<?> pacientesForLocalNascimentoIdMorada) {
		this.idMorada = idMorada;
		this.pais = pais;
		this.regiao = regiao;
		this.cidade = cidade;
		this.familiarsForMoradaIdMorada = familiarsForMoradaIdMorada;
		this.familiarsForLocalNascimentoIdMorada = familiarsForLocalNascimentoIdMorada;
		this.eventos = eventos;
		this.pacientesForMoradaIdMorada = pacientesForMoradaIdMorada;
		this.pacientesForLocalNascimentoIdMorada = pacientesForLocalNascimentoIdMorada;
	}

	public int getIdMorada() {
		return this.idMorada;
	}

	public void setIdMorada(int idMorada) {
		this.idMorada = idMorada;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getRegiao() {
		return this.regiao;
	}

	public void setRegiao(String regiao) {
		this.regiao = regiao;
	}

	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public List<?> getFamiliarsForMoradaIdMorada() {
		return this.familiarsForMoradaIdMorada;
	}

	public void setFamiliarsForMoradaIdMorada(List<?> familiarsForMoradaIdMorada) {
		this.familiarsForMoradaIdMorada = familiarsForMoradaIdMorada;
	}

	public List<?> getFamiliarsForLocalNascimentoIdMorada() {
		return this.familiarsForLocalNascimentoIdMorada;
	}

	public void setFamiliarsForLocalNascimentoIdMorada(List<?> familiarsForLocalNascimentoIdMorada) {
		this.familiarsForLocalNascimentoIdMorada = familiarsForLocalNascimentoIdMorada;
	}

	public List<?> getEventos() {
		return this.eventos;
	}

	public void setEventos(List<?> eventos) {
		this.eventos = eventos;
	}

	public List<?> getPacientesForMoradaIdMorada() {
		return this.pacientesForMoradaIdMorada;
	}

	public void setPacientesForMoradaIdMorada(List<?> pacientesForMoradaIdMorada) {
		this.pacientesForMoradaIdMorada = pacientesForMoradaIdMorada;
	}

	public List<?> getPacientesForLocalNascimentoIdMorada() {
		return this.pacientesForLocalNascimentoIdMorada;
	}

	public void setPacientesForLocalNascimentoIdMorada(List<?> pacientesForLocalNascimentoIdMorada) {
		this.pacientesForLocalNascimentoIdMorada = pacientesForLocalNascimentoIdMorada;
	}

}
