-- MySQL Script generated by MySQL Workbench
-- 09/01/15 20:49:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema memDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `memDb` ;
CREATE SCHEMA IF NOT EXISTS `memDb` DEFAULT CHARACTER SET utf8 ;
USE `memDb` ;

-- -----------------------------------------------------
-- Table `memDb`.`Utilizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Utilizador` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Utilizador` (
  `idUtilizador` INT NOT NULL,
  `nomeUtilizador` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipoUtilizador` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilizador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memDb`.`Morada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Morada` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Morada` (
  `idMorada` INT NOT NULL,
  `pais` VARCHAR(45) NULL,
  `regiao` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMorada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memDb`.`Familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Familiar` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Familiar` (
  `idFamiliar` INT NOT NULL,
  `nomeCompleto` VARCHAR(45) NULL,
  `nomeProprio` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `idLocalNascimento` INT NOT NULL,
  `idMorada` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `telefone` INT(9) NULL,
  `eCuidador` TINYINT(1) NULL,
  `dataObito` DATE NULL,
  `idUtilizador` INT NULL,
  PRIMARY KEY (`idFamiliar`),
  CONSTRAINT `fk_Familiar_Utilizador1`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `memDb`.`Utilizador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Familiar_Morada1`
    FOREIGN KEY (`idLocalNascimento`)
    REFERENCES `memDb`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Familiar_Morada2`
    FOREIGN KEY (`idMorada`)
    REFERENCES `memDb`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Familiar_Utilizador1_idx` ON `memDb`.`Familiar` (`idUtilizador` ASC);

CREATE INDEX `fk_Familiar_Morada1_idx` ON `memDb`.`Familiar` (`idLocalNascimento` ASC);

CREATE INDEX `fk_Familiar_Morada2_idx` ON `memDb`.`Familiar` (`idMorada` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Tecnico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Tecnico` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Tecnico` (
  `idTecnico` INT NOT NULL,
  `nomeProprio` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `idUtilizador` INT NOT NULL,
  PRIMARY KEY (`idTecnico`),
  CONSTRAINT `fk_Tecnico_Utilizador1`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `memDb`.`Utilizador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tecnico_Utilizador1_idx` ON `memDb`.`Tecnico` (`idUtilizador` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `nomeCompleto` VARCHAR(45) NULL,
  `nomeProprio` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `idLocalNascimento` INT NOT NULL,
  `idMorada` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `nivelDoenca` INT NULL,
  `nomeMedico` VARCHAR(45) NULL,
  `especialidade_medico` VARCHAR(45) NULL,
  `nivelSessao` INT NULL,
  `idTecnico` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `fk_Paciente_Morada1`
    FOREIGN KEY (`idLocalNascimento`)
    REFERENCES `memDb`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Morada2`
    FOREIGN KEY (`idMorada`)
    REFERENCES `memDb`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Tecnico1`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `memDb`.`Tecnico` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_Morada1_idx` ON `memDb`.`Paciente` (`idLocalNascimento` ASC);

CREATE INDEX `fk_Paciente_Morada2_idx` ON `memDb`.`Paciente` (`idMorada` ASC);

CREATE INDEX `fk_Paciente_Tecnico1_idx` ON `memDb`.`Paciente` (`idTecnico` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`RelacaoPacienteFamiliar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`RelacaoPacienteFamiliar` ;

CREATE TABLE IF NOT EXISTS `memDb`.`RelacaoPacienteFamiliar` (
  `idRelacaoPacienteFamiliar` INT NOT NULL,
  `tipoRelacao` VARCHAR(45) NULL,
  `idPaciente` INT NOT NULL,
  `idFamiliar` INT NOT NULL,
  PRIMARY KEY (`idRelacaoPacienteFamiliar`, `idPaciente`, `idFamiliar`),
  CONSTRAINT `fk_Relacao_Paciente_Familiar_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `memDb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relacao_Paciente_Familiar_Familiar1`
    FOREIGN KEY (`idFamiliar`)
    REFERENCES `memDb`.`Familiar` (`idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Relacao_Paciente_Familiar_Paciente1_idx` ON `memDb`.`RelacaoPacienteFamiliar` (`idPaciente` ASC);

CREATE INDEX `fk_Relacao_Paciente_Familiar_Familiar1_idx` ON `memDb`.`RelacaoPacienteFamiliar` (`idFamiliar` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`RelacaoFamiliarFamiliar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`RelacaoFamiliarFamiliar` ;

CREATE TABLE IF NOT EXISTS `memDb`.`RelacaoFamiliarFamiliar` (
  `idRelacaoFamiliarFamiliar` INT NOT NULL,
  `tipoRelacao` VARCHAR(45) NULL,
  `idFamiliar` INT NOT NULL,
  `idFamiliar1` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idRelacaoFamiliarFamiliar`, `idFamiliar`, `idFamiliar1`),
  CONSTRAINT `fk_Relacao_Familiar_Familiar_Familiar1`
    FOREIGN KEY (`idFamiliar`)
    REFERENCES `memDb`.`Familiar` (`idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relacao_Familiar_Familiar_Familiar2`
    FOREIGN KEY (`idFamiliar1`)
    REFERENCES `memDb`.`Familiar` (`idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RelacaoFamiliarFamiliar_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `memDb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Relacao_Familiar_Familiar_Familiar1_idx` ON `memDb`.`RelacaoFamiliarFamiliar` (`idFamiliar` ASC);

CREATE INDEX `fk_Relacao_Familiar_Familiar_Familiar2_idx` ON `memDb`.`RelacaoFamiliarFamiliar` (`idFamiliar1` ASC);

CREATE INDEX `fk_RelacaoFamiliarFamiliar_Paciente1_idx` ON `memDb`.`RelacaoFamiliarFamiliar` (`idPaciente` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Imagem` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Imagem` (
  `idImagem` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `imagem` LONGBLOB NULL,
  PRIMARY KEY (`idImagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memDb`.`Interacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Interacao` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Interacao` (
  `idInteracao` INT NOT NULL,
  `data` DATE NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idInteracao`),
  CONSTRAINT `fk_Interacao_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `memDb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Interacao_Paciente1_idx` ON `memDb`.`Interacao` (`idPaciente` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memDb`.`Jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Jogo` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Jogo` (
  `idJogo` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `idCategoria` INT NOT NULL,
  `idInteracao` INT NOT NULL,
  PRIMARY KEY (`idJogo`),
  CONSTRAINT `fk_Jogo_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `memDb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_Interacao1`
    FOREIGN KEY (`idInteracao`)
    REFERENCES `memDb`.`Interacao` (`idInteracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Jogo_Categoria1_idx` ON `memDb`.`Jogo` (`idCategoria` ASC);

CREATE INDEX `fk_Jogo_Interacao1_idx` ON `memDb`.`Jogo` (`idInteracao` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Questionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Questionario` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Questionario` (
  `idQuestionario` INT NOT NULL,
  `numPerguntas` INT NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `idCategoria` INT NOT NULL,
  `idInteracao` INT NOT NULL,
  PRIMARY KEY (`idQuestionario`),
  CONSTRAINT `fk_Questionario_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `memDb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questionario_Interacao1`
    FOREIGN KEY (`idInteracao`)
    REFERENCES `memDb`.`Interacao` (`idInteracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Questionario_Categoria1_idx` ON `memDb`.`Questionario` (`idCategoria` ASC);

CREATE INDEX `fk_Questionario_Interacao1_idx` ON `memDb`.`Questionario` (`idInteracao` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Interesse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Interesse` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Interesse` (
  `idInteresse` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInteresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memDb`.`Atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Atividade` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Atividade` (
  `idAtividade` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idAtividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memDb`.`PacienteHasInteresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`PacienteHasInteresse` ;

CREATE TABLE IF NOT EXISTS `memDb`.`PacienteHasInteresse` (
  `idInteresse` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idInteresse`, `idPaciente`),
  CONSTRAINT `fk_Paciente_has_Interesse_Interesse1`
    FOREIGN KEY (`idInteresse`)
    REFERENCES `memDb`.`Interesse` (`idInteresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Interesse_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `memDb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_has_Interesse_Interesse1_idx` ON `memDb`.`PacienteHasInteresse` (`idInteresse` ASC);

CREATE INDEX `fk_Paciente_has_Interesse_Paciente1_idx` ON `memDb`.`PacienteHasInteresse` (`idPaciente` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`PacienteHasAtividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`PacienteHasAtividade` ;

CREATE TABLE IF NOT EXISTS `memDb`.`PacienteHasAtividade` (
  `idAtividade` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idAtividade`, `idPaciente`),
  CONSTRAINT `fk_Paciente_has_Atividade_Atividade1`
    FOREIGN KEY (`idAtividade`)
    REFERENCES `memDb`.`Atividade` (`idAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Atividade_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `memDb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_has_Atividade_Atividade1_idx` ON `memDb`.`PacienteHasAtividade` (`idAtividade` ASC);

CREATE INDEX `fk_Paciente_has_Atividade_Paciente1_idx` ON `memDb`.`PacienteHasAtividade` (`idPaciente` ASC);


-- -----------------------------------------------------
-- Table `memDb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memDb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `memDb`.`Evento` (
  `idEvento` INT NOT NULL,
  `data` DATE NULL,
  `tipoEvento` VARCHAR(45) NULL,
  `idLocalEvento` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `idPaciente` INT NOT NULL,
  `idFamiliar` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idPaciente`),
  CONSTRAINT `fk_Evento_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `memDb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Familiar1`
    FOREIGN KEY (`idFamiliar`)
    REFERENCES `memDb`.`Familiar` (`idFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Morada1`
    FOREIGN KEY (`idLocalEvento`)
    REFERENCES `memDb`.`Morada` (`idMorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Evento_Paciente1_idx` ON `memDb`.`Evento` (`idPaciente` ASC);

CREATE INDEX `fk_Evento_Familiar1_idx` ON `memDb`.`Evento` (`idFamiliar` ASC);

CREATE INDEX `fk_Evento_Morada1_idx` ON `memDb`.`Evento` (`idLocalEvento` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
