package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Atividade generated by hbm2java
 */
@Entity
@Table(name = "atividade", catalog = "memdb")
public class Atividade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAtividade;
	private String nome;
	private List<Paciente> pacientes = new ArrayList<Paciente>(0);

	public Atividade() {
	}

	public Atividade(int idAtividade) {
		this.idAtividade = idAtividade;
	}

	public Atividade(int idAtividade, String nome, List<Paciente> pacientes) {
		this.idAtividade = idAtividade;
		this.nome = nome;
		this.pacientes = pacientes;
	}

	@Id

	@Column(name = "idAtividade", unique = true, nullable = false)
	public int getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(int idAtividade) {
		this.idAtividade = idAtividade;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "pacientehasatividade", catalog = "memdb", joinColumns = {
			@JoinColumn(name = "idAtividade", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idPaciente", nullable = false, updatable = false) })
	public List<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
