package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;

/**
 * EventoId generated by hbm2java
 */
@Embeddable
public class EventoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEvento;
	private int idPaciente;

	public EventoId() {
	}

	public EventoId(int idEvento, int idPaciente) {
		this.idEvento = idEvento;
		this.idPaciente = idPaciente;
	}
	@GeneratedValue
	@Column(name = "idEvento", nullable = false)
	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	@Column(name = "idPaciente", nullable = false)
	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventoId))
			return false;
		EventoId castOther = (EventoId) other;

		return (this.getIdEvento() == castOther.getIdEvento()) && (this.getIdPaciente() == castOther.getIdPaciente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEvento();
		result = 37 * result + this.getIdPaciente();
		return result;
	}

	@Override
	public String toString() {
		return "EventoId [idEvento=" + idEvento + ", idPaciente=" + idPaciente + "]";
	}

}
