package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Evento generated by hbm2java
 */
@Entity
public class Evento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idEvento;
	@ManyToOne
	private Familiar familiar;
	@ManyToOne
	private Morada morada;
	@ManyToOne
	private Paciente paciente;
	private Date data;
	private String tipoDeEvento;
	private String descricao;

	public Evento() {
	}

	public Evento(int idEvento, Morada morada, Paciente paciente) {
		this.idEvento = idEvento;
		this.morada = morada;
		this.paciente = paciente;
	}

	public Evento(int idEvento, Familiar familiar, Morada morada, Paciente paciente, Date data, String tipoDeEvento,
			String descricao) {
		this.idEvento = idEvento;
		this.familiar = familiar;
		this.morada = morada;
		this.paciente = paciente;
		this.data = data;
		this.tipoDeEvento = tipoDeEvento;
		this.descricao = descricao;
	}

	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	public Familiar getFamiliar() {
		return this.familiar;
	}

	public void setFamiliar(Familiar familiar) {
		this.familiar = familiar;
	}

	public Morada getMorada() {
		return this.morada;
	}

	public void setMorada(Morada morada) {
		this.morada = morada;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getTipoDeEvento() {
		return this.tipoDeEvento;
	}

	public void setTipoDeEvento(String tipoDeEvento) {
		this.tipoDeEvento = tipoDeEvento;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
