package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Familiar generated by hbm2java
 */
@Entity
public class Familiar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idFamiliar;
	@ManyToOne
	private Morada moradaByMoradaIdMorada;
	@ManyToOne
	private Morada moradaByLocalNascimentoIdMorada;
	@ManyToOne
	private Utilizador utilizador;
	private String nomeCompleto;
	private String nomeProprio;
	private String apelido;
	private Date dataDeNascimento;
	private String genero;
	private String estadoCivil;
	private String profissao;
	private Integer telefone;
	private Boolean ECuidador;
	private String nomeUtilizador;
	private String password;
	private Date dataDeObito;
	
	//TODO acabar os tipos de listas
	private List<?> eventos = new ArrayList<Object>(0);
	private List<?> relacaoPacienteFamiliars = new ArrayList<Object>(0);
	private List<?> relacaoFamiliarFamiliarsForFamiliarIdFamiliar1 = new ArrayList<Object>(0);
	private List<?> relacaoFamiliarFamiliarsForFamiliarIdFamiliar = new ArrayList<Object>(0);

	public Familiar() {
	}

	public Familiar(int idFamiliar, Morada moradaByMoradaIdMorada, Morada moradaByLocalNascimentoIdMorada,
			Utilizador utilizador) {
		this.idFamiliar = idFamiliar;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.utilizador = utilizador;
	}

	public Familiar(int idFamiliar, Morada moradaByMoradaIdMorada, Morada moradaByLocalNascimentoIdMorada,
			Utilizador utilizador, String nomeCompleto, String nomeProprio, String apelido, Date dataDeNascimento,
			String genero, String estadoCivil, String profissao, Integer telefone, Boolean ECuidador,
			String nomeUtilizador, String password, Date dataDeObito, List<?> eventos, List<?> relacaoPacienteFamiliars,
			List<?> relacaoFamiliarFamiliarsForFamiliarIdFamiliar1, List<?> relacaoFamiliarFamiliarsForFamiliarIdFamiliar) {
		this.idFamiliar = idFamiliar;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.utilizador = utilizador;
		this.nomeCompleto = nomeCompleto;
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.dataDeNascimento = dataDeNascimento;
		this.genero = genero;
		this.estadoCivil = estadoCivil;
		this.profissao = profissao;
		this.telefone = telefone;
		this.ECuidador = ECuidador;
		this.nomeUtilizador = nomeUtilizador;
		this.password = password;
		this.dataDeObito = dataDeObito;
		this.eventos = eventos;
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar1 = relacaoFamiliarFamiliarsForFamiliarIdFamiliar1;
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar = relacaoFamiliarFamiliarsForFamiliarIdFamiliar;
	}

	public int getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(int idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	public Morada getMoradaByMoradaIdMorada() {
		return this.moradaByMoradaIdMorada;
	}

	public void setMoradaByMoradaIdMorada(Morada moradaByMoradaIdMorada) {
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
	}

	public Morada getMoradaByLocalNascimentoIdMorada() {
		return this.moradaByLocalNascimentoIdMorada;
	}

	public void setMoradaByLocalNascimentoIdMorada(Morada moradaByLocalNascimentoIdMorada) {
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
	}

	public Utilizador getUtilizador() {
		return this.utilizador;
	}

	public void setUtilizador(Utilizador utilizador) {
		this.utilizador = utilizador;
	}

	public String getNomeCompleto() {
		return this.nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	public String getNomeProprio() {
		return this.nomeProprio;
	}

	public void setNomeProprio(String nomeProprio) {
		this.nomeProprio = nomeProprio;
	}

	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public Date getDataDeNascimento() {
		return this.dataDeNascimento;
	}

	public void setDataDeNascimento(Date dataDeNascimento) {
		this.dataDeNascimento = dataDeNascimento;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public String getProfissao() {
		return this.profissao;
	}

	public void setProfissao(String profissao) {
		this.profissao = profissao;
	}

	public Integer getTelefone() {
		return this.telefone;
	}

	public void setTelefone(Integer telefone) {
		this.telefone = telefone;
	}

	public Boolean getECuidador() {
		return this.ECuidador;
	}

	public void setECuidador(Boolean ECuidador) {
		this.ECuidador = ECuidador;
	}

	public String getNomeUtilizador() {
		return this.nomeUtilizador;
	}

	public void setNomeUtilizador(String nomeUtilizador) {
		this.nomeUtilizador = nomeUtilizador;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getDataDeObito() {
		return this.dataDeObito;
	}

	public void setDataDeObito(Date dataDeObito) {
		this.dataDeObito = dataDeObito;
	}

	public List<?> getEventos() {
		return this.eventos;
	}

	public void setEventos(List<?> eventos) {
		this.eventos = eventos;
	}

	public List<?> getRelacaoPacienteFamiliars() {
		return this.relacaoPacienteFamiliars;
	}

	public void setRelacaoPacienteFamiliars(List<?> relacaoPacienteFamiliars) {
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
	}

	public List<?> getRelacaoFamiliarFamiliarsForFamiliarIdFamiliar1() {
		return this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar1;
	}

	public void setRelacaoFamiliarFamiliarsForFamiliarIdFamiliar1(List<?> relacaoFamiliarFamiliarsForFamiliarIdFamiliar1) {
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar1 = relacaoFamiliarFamiliarsForFamiliarIdFamiliar1;
	}

	public List<?> getRelacaoFamiliarFamiliarsForFamiliarIdFamiliar() {
		return this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar;
	}

	public void setRelacaoFamiliarFamiliarsForFamiliarIdFamiliar(List<?> relacaoFamiliarFamiliarsForFamiliarIdFamiliar) {
		this.relacaoFamiliarFamiliarsForFamiliarIdFamiliar = relacaoFamiliarFamiliarsForFamiliarIdFamiliar;
	}

}
