package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Imagem generated by hbm2java
 */
@Entity
@Table(name = "imagem", catalog = "memdb")
public class Imagem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idImagem;
	private String nome;
	private byte[] imagem;

	public Imagem() {
	}

	public Imagem(int idImagem) {
		this.idImagem = idImagem;
	}

	public Imagem(int idImagem, String nome, byte[] imagem) {
		this.idImagem = idImagem;
		this.nome = nome;
		this.imagem = imagem;
	}

	@Id

	@Column(name = "idImagem", unique = true, nullable = false)
	public int getIdImagem() {
		return this.idImagem;
	}

	public void setIdImagem(int idImagem) {
		this.idImagem = idImagem;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "imagem")
	public byte[] getImagem() {
		return this.imagem;
	}

	public void setImagem(byte[] imagem) {
		this.imagem = imagem;
	}

}
