package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Interesse generated by hbm2java
 */
@Entity
@Table(name = "interesse", catalog = "memdb")
public class Interesse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idInteresse;
	private String nome;
	private List<Paciente> pacientes = new ArrayList<Paciente>(0);

	public Interesse() {
	}

	public Interesse(int idInteresse, String nome) {
		this.idInteresse = idInteresse;
		this.nome = nome;
	}

	public Interesse(int idInteresse, String nome, List<Paciente> pacientes) {
		this.idInteresse = idInteresse;
		this.nome = nome;
		this.pacientes = pacientes;
	}

	@Id

	@Column(name = "idInteresse", unique = true, nullable = false)
	public int getIdInteresse() {
		return this.idInteresse;
	}

	public void setIdInteresse(int idInteresse) {
		this.idInteresse = idInteresse;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "pacientehasinteresse", catalog = "memdb", joinColumns = {
			@JoinColumn(name = "idInteresse", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idPaciente", nullable = false, updatable = false) })
	public List<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
