package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Interesse generated by hbm2java
 */
@Entity
public class Interesse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idInteresse;
	private String nome;
	private List<Paciente> pacientes = new ArrayList<Paciente>(0);

	public Interesse() {
	}

	public Interesse(int idInteresse, String nome) {
		this.idInteresse = idInteresse;
		this.nome = nome;
	}

	public Interesse(int idInteresse, String nome, List<Paciente> pacientes) {
		this.idInteresse = idInteresse;
		this.nome = nome;
		this.pacientes = pacientes;
	}

	public int getIdInteresse() {
		return this.idInteresse;
	}

	public void setIdInteresse(int idInteresse) {
		this.idInteresse = idInteresse;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<?> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
