package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jogo generated by hbm2java
 */
@Entity
@Table(name = "jogo", catalog = "memdb")
public class Jogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idJogo;
	private Categoria categoria;
	private Interacao interacao;
	private String nome;
	private String nivel;

	public Jogo() {
	}

	public Jogo(int idJogo, Categoria categoria, Interacao interacao, String nome, String nivel) {
		this.idJogo = idJogo;
		this.categoria = categoria;
		this.interacao = interacao;
		this.nome = nome;
		this.nivel = nivel;
	}

	@Id

	@Column(name = "idJogo", unique = true, nullable = false)
	public int getIdJogo() {
		return this.idJogo;
	}

	public void setIdJogo(int idJogo) {
		this.idJogo = idJogo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInteracao", nullable = false)
	public Interacao getInteracao() {
		return this.interacao;
	}

	public void setInteracao(Interacao interacao) {
		this.interacao = interacao;
	}

	@Column(name = "Nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "nivel", nullable = false, length = 45)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

}
