package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Morada generated by hbm2java
 */
@Entity
@Table(name = "morada", catalog = "memdb")
public class Morada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idMorada;
	private String pais;
	private String regiao;
	private String cidade;
	private List<Familiar> familiarsForIdLocalNascimento = new ArrayList<Familiar>(0);
	private List<Evento> eventos = new ArrayList<Evento>(0);
	private List<Paciente> pacientesForIdLocalNascimento = new ArrayList<Paciente>(0);
	private List<Familiar> familiarsForIdMorada = new ArrayList<Familiar>(0);
	private List<Paciente> pacientesForIdMorada = new ArrayList<Paciente>(0);

	public Morada() {
	}

	public Morada(int idMorada) {
		this.idMorada = idMorada;
	}

	public Morada(int idMorada, String pais, String regiao, String cidade, List<Familiar> familiarsForIdLocalNascimento,
			List<Evento> eventos, List<Paciente> pacientesForIdLocalNascimento, List<Familiar> familiarsForIdMorada, List<Paciente> pacientesForIdMorada) {
		this.idMorada = idMorada;
		this.pais = pais;
		this.regiao = regiao;
		this.cidade = cidade;
		this.familiarsForIdLocalNascimento = familiarsForIdLocalNascimento;
		this.eventos = eventos;
		this.pacientesForIdLocalNascimento = pacientesForIdLocalNascimento;
		this.familiarsForIdMorada = familiarsForIdMorada;
		this.pacientesForIdMorada = pacientesForIdMorada;
	}

	@Id
	@GeneratedValue
	@Column(name = "idMorada", unique = true, nullable = false)
	public int getIdMorada() {
		return this.idMorada;
	}

	public void setIdMorada(int idMorada) {
		this.idMorada = idMorada;
	}

	@Column(name = "pais", length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "regiao", length = 45)
	public String getRegiao() {
		return this.regiao;
	}

	public void setRegiao(String regiao) {
		this.regiao = regiao;
	}

	@Column(name = "cidade", length = 45)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moradaByIdLocalNascimento")
	public List<Familiar> getFamiliarsForIdLocalNascimento() {
		return this.familiarsForIdLocalNascimento;
	}

	public void setFamiliarsForIdLocalNascimento(List<Familiar> familiarsForIdLocalNascimento) {
		this.familiarsForIdLocalNascimento = familiarsForIdLocalNascimento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "morada")
	public List<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(List<Evento> eventos) {
		this.eventos = eventos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moradaByIdLocalNascimento")
	public List<Paciente> getPacientesForIdLocalNascimento() {
		return this.pacientesForIdLocalNascimento;
	}

	public void setPacientesForIdLocalNascimento(List<Paciente> pacientesForIdLocalNascimento) {
		this.pacientesForIdLocalNascimento = pacientesForIdLocalNascimento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moradaByIdMorada")
	public List<Familiar> getFamiliarsForIdMorada() {
		return this.familiarsForIdMorada;
	}

	public void setFamiliarsForIdMorada(List<Familiar> familiarsForIdMorada) {
		this.familiarsForIdMorada = familiarsForIdMorada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moradaByIdMorada")
	public List<Paciente> getPacientesForIdMorada() {
		return this.pacientesForIdMorada;
	}

	public void setPacientesForIdMorada(List<Paciente> pacientesForIdMorada) {
		this.pacientesForIdMorada = pacientesForIdMorada;
	}

	@Override
	public String toString() {
		return "Morada [idMorada=" + idMorada + ", pais=" + pais + ", regiao=" + regiao + ", cidade=" + cidade + "]";
	}

}
