package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Paciente generated by hbm2java
 */
@Entity
public class Paciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idPaciente;
	@ManyToOne
	private Morada moradaByMoradaIdMorada;
	@ManyToOne
	private Morada moradaByLocalNascimentoIdMorada;
	@ManyToOne
	private Tecnico tecnico;
	private String nomeCompleto;
	private String nomeProprio;
	private String apelido;
	private Date dataDeNascimento;
	private String genero;
	private String profissao;
	private String escolaridade;
	private String estadoCivil;
	private Integer nivelDeDoenca;
	private String nomeMedico;
	private String especialidadeMedico;
	private Integer nivelSessao;
	
	//TODO preencher tipos
	private List<?> atividades = new ArrayList<Object>(0);
	private List<?> eventos = new ArrayList<Object>(0);
	private List<?> relacaoFamiliarFamiliars = new ArrayList<Object>(0);
	private List<?> interesses = new ArrayList<Object>(0);
	private List<?> relacaoPacienteFamiliars = new ArrayList<Object>(0);
	private List<?> interacaos = new ArrayList<Object>(0);

	public Paciente() {
	}

	public Paciente(int idPaciente, Morada moradaByMoradaIdMorada, Morada moradaByLocalNascimentoIdMorada,
			Tecnico tecnico) {
		this.idPaciente = idPaciente;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.tecnico = tecnico;
	}

	public Paciente(int idPaciente, Morada moradaByMoradaIdMorada, Morada moradaByLocalNascimentoIdMorada,
			Tecnico tecnico, String nomeCompleto, String nomeProprio, String apelido, Date dataDeNascimento,
			String genero, String profissao, String escolaridade, String estadoCivil, Integer nivelDeDoenca,
			String nomeMedico, String especialidadeMedico, Integer nivelSessao, List<?> atividades, List<?> eventos,
			List<?> relacaoFamiliarFamiliars, List<?> interesses, List<?> relacaoPacienteFamiliars, List<?> interacaos) {
		this.idPaciente = idPaciente;
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
		this.tecnico = tecnico;
		this.nomeCompleto = nomeCompleto;
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.dataDeNascimento = dataDeNascimento;
		this.genero = genero;
		this.profissao = profissao;
		this.escolaridade = escolaridade;
		this.estadoCivil = estadoCivil;
		this.nivelDeDoenca = nivelDeDoenca;
		this.nomeMedico = nomeMedico;
		this.especialidadeMedico = especialidadeMedico;
		this.nivelSessao = nivelSessao;
		this.atividades = atividades;
		this.eventos = eventos;
		this.relacaoFamiliarFamiliars = relacaoFamiliarFamiliars;
		this.interesses = interesses;
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
		this.interacaos = interacaos;
	}

	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	public Morada getMoradaByMoradaIdMorada() {
		return this.moradaByMoradaIdMorada;
	}

	public void setMoradaByMoradaIdMorada(Morada moradaByMoradaIdMorada) {
		this.moradaByMoradaIdMorada = moradaByMoradaIdMorada;
	}

	public Morada getMoradaByLocalNascimentoIdMorada() {
		return this.moradaByLocalNascimentoIdMorada;
	}

	public void setMoradaByLocalNascimentoIdMorada(Morada moradaByLocalNascimentoIdMorada) {
		this.moradaByLocalNascimentoIdMorada = moradaByLocalNascimentoIdMorada;
	}

	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	public String getNomeCompleto() {
		return this.nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	public String getNomeProprio() {
		return this.nomeProprio;
	}

	public void setNomeProprio(String nomeProprio) {
		this.nomeProprio = nomeProprio;
	}

	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	public Date getDataDeNascimento() {
		return this.dataDeNascimento;
	}

	public void setDataDeNascimento(Date dataDeNascimento) {
		this.dataDeNascimento = dataDeNascimento;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getProfissao() {
		return this.profissao;
	}

	public void setProfissao(String profissao) {
		this.profissao = profissao;
	}

	public String getEscolaridade() {
		return this.escolaridade;
	}

	public void setEscolaridade(String escolaridade) {
		this.escolaridade = escolaridade;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public Integer getNivelDeDoenca() {
		return this.nivelDeDoenca;
	}

	public void setNivelDeDoenca(Integer nivelDeDoenca) {
		this.nivelDeDoenca = nivelDeDoenca;
	}

	public String getNomeMedico() {
		return this.nomeMedico;
	}

	public void setNomeMedico(String nomeMedico) {
		this.nomeMedico = nomeMedico;
	}

	public String getEspecialidadeMedico() {
		return this.especialidadeMedico;
	}

	public void setEspecialidadeMedico(String especialidadeMedico) {
		this.especialidadeMedico = especialidadeMedico;
	}

	public Integer getNivelSessao() {
		return this.nivelSessao;
	}

	public void setNivelSessao(Integer nivelSessao) {
		this.nivelSessao = nivelSessao;
	}

	public List<?> getAtividades() {
		return this.atividades;
	}

	public void setAtividades(List<?> atividades) {
		this.atividades = atividades;
	}

	public List<?> getEventos() {
		return this.eventos;
	}

	public void setEventos(List<?> eventos) {
		this.eventos = eventos;
	}

	public List<?> getRelacaoFamiliarFamiliars() {
		return this.relacaoFamiliarFamiliars;
	}

	public void setRelacaoFamiliarFamiliars(List<?> relacaoFamiliarFamiliars) {
		this.relacaoFamiliarFamiliars = relacaoFamiliarFamiliars;
	}

	public List<?> getInteresses() {
		return this.interesses;
	}

	public void setInteresses(List<?> interesses) {
		this.interesses = interesses;
	}

	public List<?> getRelacaoPacienteFamiliars() {
		return this.relacaoPacienteFamiliars;
	}

	public void setRelacaoPacienteFamiliars(List<?> relacaoPacienteFamiliars) {
		this.relacaoPacienteFamiliars = relacaoPacienteFamiliars;
	}

	public List<?> getInteracaos() {
		return this.interacaos;
	}

	public void setInteracaos(List<?> interacaos) {
		this.interacaos = interacaos;
	}

}
