package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questionario generated by hbm2java
 */
@Entity
@Table(name = "questionario", catalog = "memdb")
public class Questionario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idQuestionario;
	private Categoria categoria;
	private Interacao interacao;
	private int numPerguntas;
	private String nivel;

	public Questionario() {
	}

	public Questionario(int idQuestionario, Categoria categoria, Interacao interacao, int numPerguntas, String nivel) {
		this.idQuestionario = idQuestionario;
		this.categoria = categoria;
		this.interacao = interacao;
		this.numPerguntas = numPerguntas;
		this.nivel = nivel;
	}

	@Id

	@Column(name = "idQuestionario", unique = true, nullable = false)
	public int getIdQuestionario() {
		return this.idQuestionario;
	}

	public void setIdQuestionario(int idQuestionario) {
		this.idQuestionario = idQuestionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInteracao", nullable = false)
	public Interacao getInteracao() {
		return this.interacao;
	}

	public void setInteracao(Interacao interacao) {
		this.interacao = interacao;
	}

	@Column(name = "numPerguntas", nullable = false)
	public int getNumPerguntas() {
		return this.numPerguntas;
	}

	public void setNumPerguntas(int numPerguntas) {
		this.numPerguntas = numPerguntas;
	}

	@Column(name = "nivel", nullable = false, length = 45)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

}
