package com.mem.app.model;
// Generated 2/Ago/2015 23:24:41 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * RelacaoFamiliarFamiliar generated by hbm2java
 */
@Entity
public class RelacaoFamiliarFamiliar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@ManyToOne
	private RelacaoFamiliarFamiliarId id;
	@ManyToOne
	private Familiar familiarByFamiliarIdFamiliar1;
	@ManyToOne
	private Familiar familiarByFamiliarIdFamiliar;
	@ManyToOne
	private Paciente paciente;
	private String tipoRelacao;

	public RelacaoFamiliarFamiliar() {
	}

	public RelacaoFamiliarFamiliar(RelacaoFamiliarFamiliarId id, Familiar familiarByFamiliarIdFamiliar1,
			Familiar familiarByFamiliarIdFamiliar, Paciente paciente) {
		this.id = id;
		this.familiarByFamiliarIdFamiliar1 = familiarByFamiliarIdFamiliar1;
		this.familiarByFamiliarIdFamiliar = familiarByFamiliarIdFamiliar;
		this.paciente = paciente;
	}

	public RelacaoFamiliarFamiliar(RelacaoFamiliarFamiliarId id, Familiar familiarByFamiliarIdFamiliar1,
			Familiar familiarByFamiliarIdFamiliar, Paciente paciente, String tipoRelacao) {
		this.id = id;
		this.familiarByFamiliarIdFamiliar1 = familiarByFamiliarIdFamiliar1;
		this.familiarByFamiliarIdFamiliar = familiarByFamiliarIdFamiliar;
		this.paciente = paciente;
		this.tipoRelacao = tipoRelacao;
	}

	public RelacaoFamiliarFamiliarId getId() {
		return this.id;
	}

	public void setId(RelacaoFamiliarFamiliarId id) {
		this.id = id;
	}

	public Familiar getFamiliarByFamiliarIdFamiliar1() {
		return this.familiarByFamiliarIdFamiliar1;
	}

	public void setFamiliarByFamiliarIdFamiliar1(Familiar familiarByFamiliarIdFamiliar1) {
		this.familiarByFamiliarIdFamiliar1 = familiarByFamiliarIdFamiliar1;
	}

	public Familiar getFamiliarByFamiliarIdFamiliar() {
		return this.familiarByFamiliarIdFamiliar;
	}

	public void setFamiliarByFamiliarIdFamiliar(Familiar familiarByFamiliarIdFamiliar) {
		this.familiarByFamiliarIdFamiliar = familiarByFamiliarIdFamiliar;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public String getTipoRelacao() {
		return this.tipoRelacao;
	}

	public void setTipoRelacao(String tipoRelacao) {
		this.tipoRelacao = tipoRelacao;
	}

}
