package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;

/**
 * RelacaoFamiliarFamiliar generated by hbm2java
 */
@Embeddable
public class RelacaoFamiliarFamiliarId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRelacao;
	private int idFamiliar;
	private int idFamiliar1;

	public RelacaoFamiliarFamiliarId() {
	}

	public RelacaoFamiliarFamiliarId(int idRelacao, int idFamiliar, int idFamiliar1) {
		this.idRelacao = idRelacao;
		this.idFamiliar = idFamiliar;
		this.idFamiliar1 = idFamiliar1;
	}
	@GeneratedValue
	@Column(name = "idRelacao", nullable = false)
	public int getIdRelacao() {
		return this.idRelacao;
	}

	public void setIdRelacao(int idRelacao) {
		this.idRelacao = idRelacao;
	}

	@Column(name = "idFamiliar", nullable = false)
	public int getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(int idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	@Column(name = "idFamiliar1", nullable = false)
	public int getIdFamiliar1() {
		return this.idFamiliar1;
	}

	public void setIdFamiliar1(int idFamiliar1) {
		this.idFamiliar1 = idFamiliar1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelacaoFamiliarFamiliarId))
			return false;
		RelacaoFamiliarFamiliarId castOther = (RelacaoFamiliarFamiliarId) other;

		return (this.getIdRelacao() == castOther.getIdRelacao())
				&& (this.getIdFamiliar() == castOther.getIdFamiliar())
				&& (this.getIdFamiliar1() == castOther.getIdFamiliar1());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRelacao();
		result = 37 * result + this.getIdFamiliar();
		result = 37 * result + this.getIdFamiliar1();
		return result;
	}

}
