package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;

/**
 * RelacaoPacienteFamiliarId generated by hbm2java
 */
@Embeddable
public class RelacaoPacienteFamiliarId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRelacao;
	private int idPaciente;
	private int idFamiliar;

	public RelacaoPacienteFamiliarId() {
	}

	public RelacaoPacienteFamiliarId(int idRelacao, int idPaciente, int idFamiliar) {
		this.idRelacao = idRelacao;
		this.idPaciente = idPaciente;
		this.idFamiliar = idFamiliar;
	}

	@GeneratedValue
	@Column(name = "idRelacao", nullable = false)
	public int getIdRelacao() {
		return this.idRelacao;
	}

	public void setIdRelacao(int idRelacao) {
		this.idRelacao = idRelacao;
	}

	@Column(name = "idPaciente", nullable = false)
	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "idFamiliar", nullable = false)
	public int getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(int idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelacaoPacienteFamiliarId))
			return false;
		RelacaoPacienteFamiliarId castOther = (RelacaoPacienteFamiliarId) other;

		return (this.getIdRelacao() == castOther.getIdRelacao())
				&& (this.getIdPaciente() == castOther.getIdPaciente())
				&& (this.getIdFamiliar() == castOther.getIdFamiliar());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRelacao();
		result = 37 * result + this.getIdPaciente();
		result = 37 * result + this.getIdFamiliar();
		return result;
	}

	@Override
	public String toString() {
		return "RelacaoPacienteFamiliarId [idRelacaoPacienteFamiliar=" + idRelacao + ", idPaciente="
				+ idPaciente + ", idFamiliar=" + idFamiliar + "]";
	}

}
