package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelacaofamiliarfamiliarId generated by hbm2java
 */
@Embeddable
public class RelacaofamiliarfamiliarId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRelacaoFamiliarFamiliar;
	private int idFamiliar;
	private int idFamiliar1;

	public RelacaofamiliarfamiliarId() {
	}

	public RelacaofamiliarfamiliarId(int idRelacaoFamiliarFamiliar, int idFamiliar, int idFamiliar1) {
		this.idRelacaoFamiliarFamiliar = idRelacaoFamiliarFamiliar;
		this.idFamiliar = idFamiliar;
		this.idFamiliar1 = idFamiliar1;
	}

	@Column(name = "idRelacaoFamiliarFamiliar", nullable = false)
	public int getIdRelacaoFamiliarFamiliar() {
		return this.idRelacaoFamiliarFamiliar;
	}

	public void setIdRelacaoFamiliarFamiliar(int idRelacaoFamiliarFamiliar) {
		this.idRelacaoFamiliarFamiliar = idRelacaoFamiliarFamiliar;
	}

	@Column(name = "idFamiliar", nullable = false)
	public int getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(int idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	@Column(name = "idFamiliar1", nullable = false)
	public int getIdFamiliar1() {
		return this.idFamiliar1;
	}

	public void setIdFamiliar1(int idFamiliar1) {
		this.idFamiliar1 = idFamiliar1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelacaofamiliarfamiliarId))
			return false;
		RelacaofamiliarfamiliarId castOther = (RelacaofamiliarfamiliarId) other;

		return (this.getIdRelacaoFamiliarFamiliar() == castOther.getIdRelacaoFamiliarFamiliar())
				&& (this.getIdFamiliar() == castOther.getIdFamiliar())
				&& (this.getIdFamiliar1() == castOther.getIdFamiliar1());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRelacaoFamiliarFamiliar();
		result = 37 * result + this.getIdFamiliar();
		result = 37 * result + this.getIdFamiliar1();
		return result;
	}

}
