package com.mem.app.model;
// Generated 21/Ago/2015 19:35:12 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.mem.app.model.enumerates.TipoUtilizador;

/**
 * Tecnico generated by hbm2java
 */
@Entity
@Table(name = "tecnico", catalog = "memdb")
public class Tecnico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTecnico;
	private Utilizador utilizador;
	private String nomeProprio;
	private String apelido;
	private int telefone;
	private List<Paciente> pacientes = new ArrayList<Paciente>(0);

	public Tecnico() {
	}

	public Tecnico(int idTecnico, Utilizador utilizador, String nomeProprio, String apelido, int telefone) {
		this.idTecnico = idTecnico;
		this.utilizador = utilizador;
		this.utilizador.setTipoUtilizador(TipoUtilizador.TECNICO.toString());
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.telefone = telefone;
	}

	public Tecnico(int idTecnico, Utilizador utilizador, String nomeProprio, String apelido, int telefone,
			List<Paciente> pacientes) {
		this.idTecnico = idTecnico;
		this.utilizador = utilizador;
		this.utilizador.setTipoUtilizador(TipoUtilizador.TECNICO.toString());
		this.nomeProprio = nomeProprio;
		this.apelido = apelido;
		this.telefone = telefone;
		this.pacientes = pacientes;
	}

	@Id

	@Column(name = "idTecnico", unique = true, nullable = false)
	public int getIdTecnico() {
		return this.idTecnico;
	}

	public void setIdTecnico(int idTecnico) {
		this.idTecnico = idTecnico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilizador", nullable = false)
	public Utilizador getUtilizador() {
		return this.utilizador;
	}

	public void setUtilizador(Utilizador utilizador) {
		this.utilizador = utilizador;
	}

	@Column(name = "nomeProprio", nullable = false, length = 45)
	public String getNomeProprio() {
		return this.nomeProprio;
	}

	public void setNomeProprio(String nomeProprio) {
		this.nomeProprio = nomeProprio;
	}

	@Column(name = "apelido", nullable = false, length = 45)
	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	@Column(name = "telefone", nullable = false)
	public int getTelefone() {
		return this.telefone;
	}

	public void setTelefone(int telefone) {
		this.telefone = telefone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public List<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
