package com.mem.app.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Utilizador generated by hbm2java
 */
@Entity
public class Utilizador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private int idUtilizador;
	private String nomeUtilizador;
	private String password;
	private String tipoUtilizador;
	private String email;
	
	private List<Tecnico> tecnicos = new ArrayList<Tecnico>(0);
	private List<Familiar> familiars = new ArrayList<Familiar>(0);

	public Utilizador() {
	}

	public Utilizador(int idUtilizador, String nomeUtilizador, String password, String tipoUtilizador) {
		this.idUtilizador = idUtilizador;
		this.nomeUtilizador = nomeUtilizador;
		this.password = password;
		this.tipoUtilizador = tipoUtilizador;
	}

	public Utilizador(int idUtilizador, String nomeUtilizador, String password, String tipoUtilizador, String email,  List<Tecnico> tecnicos,
			List<Familiar> familiars) {
		this.idUtilizador = idUtilizador;
		this.nomeUtilizador = nomeUtilizador;
		this.password = password;
		this.tipoUtilizador = tipoUtilizador;
		this.email = email;
		this.tecnicos = tecnicos;
		this.familiars = familiars;
	}

	public int getIdUtilizador() {
		return this.idUtilizador;
	}

	public void setIdUtilizador(int idUtilizador) {
		this.idUtilizador = idUtilizador;
	}

	public String getNomeUtilizador() {
		return this.nomeUtilizador;
	}

	public void setNomeUtilizador(String nomeUtilizador) {
		this.nomeUtilizador = nomeUtilizador;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTipoUtilizador() {
		return this.tipoUtilizador;
	}

	public void setTipoUtilizador(String tipoUtilizador) {
		this.tipoUtilizador = tipoUtilizador;
	}

	public List<Tecnico> getTecnicos() {
		return this.tecnicos;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setTecnicos(List<Tecnico> tecnicos) {
		this.tecnicos = tecnicos;
	}

	public List<Familiar> getFamiliars() {
		return this.familiars;
	}

	public void setFamiliars(List<Familiar> familiars) {
		this.familiars = familiars;
	}

}
