-- MySQL Script generated by MySQL Workbench
-- 12/21/14 16:41:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema memwebdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `memwebdb` ;

-- -----------------------------------------------------
-- Schema memwebdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `memwebdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `memwebdb` ;

-- -----------------------------------------------------
-- Table `memwebdb`.`Gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Gender` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Gender` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`MaritalStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`MaritalStatus` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`MaritalStatus` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Persons` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(32) NOT NULL,
  `MiddleName` VARCHAR(64) NOT NULL,
  `LastName` VARCHAR(32) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Gender` INT NOT NULL,
  `MaritalStatus` INT UNSIGNED NOT NULL,
  `Profession` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Patients` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Patients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Persons_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Relatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Relatives` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Relatives` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Patients_id` INT UNSIGNED NOT NULL,
  `dateOfDeath` DATE NOT NULL DEFAULT '2999-12-31',
  `caregiver` TINYINT(1) NOT NULL DEFAULT 0,
  `Persons_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Technicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Technicians` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Technicians` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Persons_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Doctors` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Doctors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `speciality` VARCHAR(64) NOT NULL,
  `Persons_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Caregivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Caregivers` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Caregivers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `caregiver` TINYINT(1) NOT NULL DEFAULT 0,
  `Persons_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Persons_id_UNIQUE` (`Persons_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Addresses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(64) NOT NULL,
  `city` VARCHAR(128) NOT NULL,
  `region` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Pictures` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Pictures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Medical_Charts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Medical_Charts` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Medical_Charts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `education` VARCHAR(64) NOT NULL DEFAULT 'Não Disponivel',
  `sicknessLevel` VARCHAR(32) NOT NULL DEFAULT 'Não Disponivel',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Events` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(32) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `dateOfOccurance` DATE NOT NULL DEFAULT '1900-01-01',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Therapy_Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Therapy_Sessions` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Therapy_Sessions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Therapy_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Therapy_Category` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Therapy_Category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Users` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`User_Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`User_Roles` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`User_Roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Exercicies_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Exercicies_Category` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Exercicies_Category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Events_has_Persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Events_has_Persons` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Events_has_Persons` (
  `Events_id` INT UNSIGNED NOT NULL,
  `Persons_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Events_id`, `Persons_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Patients_has_Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Patients_has_Addresses` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Patients_has_Addresses` (
  `Patients_id` INT UNSIGNED NOT NULL,
  `Addresses_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Patients_id`, `Addresses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Patients_has_Relatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Patients_has_Relatives` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Patients_has_Relatives` (
  `Patients_id` INT UNSIGNED NOT NULL,
  `Relatives_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Patients_id`, `Relatives_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Relatives_has_Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Relatives_has_Addresses` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Relatives_has_Addresses` (
  `Relatives_id` INT UNSIGNED NOT NULL,
  `Addresses_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Relatives_id`, `Addresses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Therapy_Sessions_has_Therapy_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Therapy_Sessions_has_Therapy_Category` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Therapy_Sessions_has_Therapy_Category` (
  `Therapy_Sessions_id` INT UNSIGNED NOT NULL,
  `Therapy_Category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Therapy_Sessions_id`, `Therapy_Category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Medical_Charts_has_Therapy_Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Medical_Charts_has_Therapy_Sessions` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Medical_Charts_has_Therapy_Sessions` (
  `Medical_Charts_id` INT UNSIGNED NOT NULL,
  `Therapy_Sessions_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Medical_Charts_id`, `Therapy_Sessions_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Events_has_Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Events_has_Pictures` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Events_has_Pictures` (
  `Events_id` INT UNSIGNED NOT NULL,
  `Pictures_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Events_id`, `Pictures_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Patients_has_Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Patients_has_Pictures` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Patients_has_Pictures` (
  `Patients_id` INT UNSIGNED NOT NULL,
  `Pictures_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Patients_id`, `Pictures_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Relatives_has_Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Relatives_has_Pictures` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Relatives_has_Pictures` (
  `Relatives_id` INT UNSIGNED NOT NULL,
  `Pictures_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Relatives_id`, `Pictures_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Users_has_User_Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Users_has_User_Roles` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Users_has_User_Roles` (
  `Users_id` INT UNSIGNED NOT NULL,
  `User_Roles_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Users_id`, `User_Roles_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Therapy_Category_has_Exercicies_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Therapy_Category_has_Exercicies_Category` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Therapy_Category_has_Exercicies_Category` (
  `Therapy_Category_id` INT UNSIGNED NOT NULL,
  `Exercicies_Category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Therapy_Category_id`, `Exercicies_Category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Patients_has_Medical_Charts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Patients_has_Medical_Charts` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Patients_has_Medical_Charts` (
  `Patients_id` INT UNSIGNED NOT NULL,
  `Medical_Charts_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Patients_id`, `Medical_Charts_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Medical_Charts_has_Technicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Medical_Charts_has_Technicians` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Medical_Charts_has_Technicians` (
  `Medical_Charts_id` INT UNSIGNED NOT NULL,
  `Technicians_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Medical_Charts_id`, `Technicians_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memwebdb`.`Medical_Charts_has_Doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `memwebdb`.`Medical_Charts_has_Doctors` ;

CREATE TABLE IF NOT EXISTS `memwebdb`.`Medical_Charts_has_Doctors` (
  `Medical_Charts_id` INT UNSIGNED NOT NULL,
  `Doctors_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Medical_Charts_id`, `Doctors_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `memwebdb`.`Gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Gender` (`id`, `description`) VALUES (1, 'Não Disponível');
INSERT INTO `memwebdb`.`Gender` (`id`, `description`) VALUES (2, 'Masculino');
INSERT INTO `memwebdb`.`Gender` (`id`, `description`) VALUES (3, 'Feminio');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`MaritalStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`MaritalStatus` (`id`, `description`) VALUES (1, 'Não Disponível');
INSERT INTO `memwebdb`.`MaritalStatus` (`id`, `description`) VALUES (2, 'Solteiro');
INSERT INTO `memwebdb`.`MaritalStatus` (`id`, `description`) VALUES (3, 'Casado');
INSERT INTO `memwebdb`.`MaritalStatus` (`id`, `description`) VALUES (4, 'Divorciado');
INSERT INTO `memwebdb`.`MaritalStatus` (`id`, `description`) VALUES (5, 'União de Facto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Persons`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Persons` (`id`, `FirstName`, `MiddleName`, `LastName`, `DateOfBirth`, `Gender`, `MaritalStatus`, `Profession`) VALUES (1, 'Não Disponível', 'Não Disponível', 'Não Disponível', '1900-01-01', 1, 1, 'Não Disponível');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Patients`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Patients` (`id`, `Persons_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Relatives`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Relatives` (`id`, `Patients_id`, `dateOfDeath`, `caregiver`, `Persons_id`) VALUES (1, 1, '2999-12-31', false, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Technicians`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Technicians` (`id`, `Persons_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Doctors`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Doctors` (`id`, `speciality`, `Persons_id`) VALUES (1, 'não disponivel', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Caregivers`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Caregivers` (`id`, `caregiver`, `Persons_id`) VALUES (1, 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Addresses`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Addresses` (`id`, `country`, `city`, `region`) VALUES (1, 'Não Disponível', 'Não Disponível', 'Não Disponível');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Pictures`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Pictures` (`id`, `image`) VALUES (1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Medical_Charts`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Medical_Charts` (`id`, `education`, `sicknessLevel`) VALUES (1, 'Não Disponível', 'Não Disponível');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Events`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Events` (`id`, `title`, `description`, `dateOfOccurance`) VALUES (1, 'Não Disponível', 'Não Disponível', '1900-01-01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Therapy_Sessions`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Therapy_Sessions` (`id`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Therapy_Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Therapy_Category` (`id`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Users` (`id`, `username`, `password`) VALUES (1, 'nousername', 'nopassword');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`User_Roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`User_Roles` (`id`, `role`) VALUES (1, 'norole');

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Exercicies_Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Exercicies_Category` (`id`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Events_has_Persons`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Events_has_Persons` (`Events_id`, `Persons_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Patients_has_Addresses`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Patients_has_Addresses` (`Patients_id`, `Addresses_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Patients_has_Relatives`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Patients_has_Relatives` (`Patients_id`, `Relatives_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Relatives_has_Addresses`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Relatives_has_Addresses` (`Relatives_id`, `Addresses_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Therapy_Sessions_has_Therapy_Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Therapy_Sessions_has_Therapy_Category` (`Therapy_Sessions_id`, `Therapy_Category_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Medical_Charts_has_Therapy_Sessions`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Medical_Charts_has_Therapy_Sessions` (`Medical_Charts_id`, `Therapy_Sessions_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Events_has_Pictures`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Events_has_Pictures` (`Events_id`, `Pictures_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Patients_has_Pictures`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Patients_has_Pictures` (`Patients_id`, `Pictures_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Relatives_has_Pictures`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Relatives_has_Pictures` (`Relatives_id`, `Pictures_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Users_has_User_Roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Users_has_User_Roles` (`Users_id`, `User_Roles_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Therapy_Category_has_Exercicies_Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Therapy_Category_has_Exercicies_Category` (`Therapy_Category_id`, `Exercicies_Category_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Patients_has_Medical_Charts`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Patients_has_Medical_Charts` (`Patients_id`, `Medical_Charts_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Medical_Charts_has_Technicians`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Medical_Charts_has_Technicians` (`Medical_Charts_id`, `Technicians_id`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `memwebdb`.`Medical_Charts_has_Doctors`
-- -----------------------------------------------------
START TRANSACTION;
USE `memwebdb`;
INSERT INTO `memwebdb`.`Medical_Charts_has_Doctors` (`Medical_Charts_id`, `Doctors_id`) VALUES (1, 1);

COMMIT;

